### ISSUE TITLE
Issue connecting to heater with aa55 protocol

### ISSUE THREAD

**Issue by zak4206** [Spettacolo83/homeassistant-vevor-heater#5]
Wondering if you might have any idea what is happening here.

![Image](https://github.com/user-attachments/assets/b051e7d5-347b-4e28-8ea3-9fa607cdc646)

Logger: custom_components.vevor_heater.coordinator
Source: custom_components/vevor_heater/coordinator.py:621
integration: Vevor Diesel Heater ([documentation](https://github.com/Spettacolo83/homeassistant-vevor-heater), [issues](https://github.com/Spettacolo83/homeassistant-vevor-heater/issues))
First occurred: 12:49:31 AM (32 occurrences)
Last logged: 1:07:20 AM

🔍 Unknown protocol, length: 18, header: 0xAA55

Logger: custom_components.vevor_heater
Source: custom_components/vevor_heater/__init__.py:70
integration: Vevor Diesel Heater ([documentation](https://github.com/Spettacolo83/homeassistant-vevor-heater), [issues](https://github.com/Spettacolo83/homeassistant-vevor-heater/issues))
First occurred: 12:24:46 AM (6 occurrences)
Last logged: 1:10:45 AM

Initial connection to Vevor Heater at xxxxxxxxxx:7C failed: No status received from heater. Setup will complete anyway and retry in background. Entities will show as unavailable until connection succeeds. Make sure the heater is powered on, in Bluetooth range, and the Vevor app is disconnected.
Initial connection to Vevor Heater at xxxxxxxxx:EA failed: No status received from heater. Setup will complete anyway and retry in background. Entities will show as unavailable until connection succeeds. Make sure the heater is powered on, in Bluetooth range, and the Vevor app is disconnected.

Macs edited out.

**Comment by Spettacolo83** [comment]
Hi @zak4206,

Thank you for reporting this issue!

## Bug Fix Released: v1.0.15

I've just released **v1.0.15** which fixes the `AttributeError: property 'config_entry' has no setter` error. This was a compatibility issue with Home Assistant 2024.1+.

Please update to v1.0.15 and try again. You can update via HACS or by downloading the latest release.

Let me know if you still have connection issues after updating!

**Comment by zak4206** [comment]
i was still having issues connecting to my heaters, modified partially the coordinator.py

here are the changes i made to make it work but it will break for other models,


        if header == 0xAA55 and len(data) == 18:
            # Protocol 1: 0xAA 0x55, 18 bytes, not encrypted
            _LOGGER.info("🔍 Detected protocol: AA55 unencrypted (mode=1)")
            self._parse_protocol_aa55(data)


and changed this to 18 aswell 


    def _parse_protocol_aa55(self, data: bytearray) -> None:
        """Parse protocol AA55 (18 bytes, unencrypted)."""
        self._protocol_mode = 1
        

changed from 20 to 18 to make it work, no power controls, (on/off) but sensors populate fully.

in this section of the code




` def _parse_response(self, data: bytearray) -> None:
        """Parse response from heater."""
        if len(data) < 17:
            _LOGGER.debug("Response too short: %d bytes", len(data))
            return

        # Check protocol type
        header = (_u8_to_number(data[0]) << 8) | _u8_to_number(data[1])
        old_protocol = self._protocol_mode

        if header == 0xAA55 and len(data) == 18:
            # Protocol 1: 0xAA 0x55, 18 bytes, not encrypted
            _LOGGER.info("🔍 Detected protocol: AA55 unencrypted (mode=1)")
            self._parse_protocol_aa55(data)
        elif header == 0xAA66 and len(data) == 20:
            # Protocol 3: 0xAA 0x66, 20 bytes, not encrypted
            _LOGGER.info("🔍 Detected protocol: AA66 unencrypted (mode=3)")
            self._parse_protocol_aa66(data)
        elif len(data) == 48:
            # Protocol 2/4: 48 bytes, encrypted
            decrypted = _decrypt_data(data)
            header = (_u8_to_number(decrypted[0]) << 8) | _u8_to_number(decrypted[1])
            _LOGGER.debug("Decrypted header: 0x%04X", header)

            if header == 0xAA55:
                _LOGGER.info("🔍 Detected protocol: AA55 encrypted (mode=2)")
                self._parse_protocol_aa55_encrypted(decrypted)
            elif header == 0xAA66:
                _LOGGER.info("🔍 Detected protocol: AA66 encrypted (mode=4)")
                self._parse_protocol_aa66_encrypted(decrypted)
            else:
                _LOGGER.warning(
                    "🔍 Unknown encrypted protocol, decrypted header: 0x%04X",
                    header
                )
        else:
            _LOGGER.warning(
                "🔍 Unknown protocol, length: %d, header: 0x%04X",
                len(data), header
            )

        # Log protocol change
        if old_protocol != self._protocol_mode:
            _LOGGER.info(
                "📋 Protocol mode changed: %d → %d (commands will now use %s format)",
                old_protocol, self._protocol_mode,
                "AA66 encrypted" if self._protocol_mode == 4 else
                "AA66 unencrypted" if self._protocol_mode == 3 else
                "AA55 encrypted" if self._protocol_mode == 2 else
                "AA55 unencrypted"
            )

    def _parse_protocol_aa55(self, data: bytearray) -> None:
        """Parse protocol AA55 (18 bytes, unencrypted)."""
        self._protocol_mode = 1
        
`
